spring:
  datasource:
    #url: jdbc:h2:tcp://localhost/~/pliatessmpa
    url: jdbc:h2:mem:pliatessmpa
    driverClassName: org.h2.Driver
    username: sa
    password:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
  thymeleaf:
    enabled: true
    encoding: UTF-8
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    cache: false
